# Generated by Django 4.0.4 on 2022-04-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='teachersjobhistory',
            options={'verbose_name': 'TeacherJobHistory', 'verbose_name_plural': 'TeachersJobHistory'},
        ),
    ]
