# Generated by Django 4.0.4 on 2022-04-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schoolapp', '0002_rename_is_current_organization_teachersjobhistory_is_current_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(default='2003-01-01'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(default='2003-01-01'),
        ),
    ]
