# Generated by Django 4.0.4 on 2022-04-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number_of_class_in_school')),
                ('class_time', models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon')], default='Morning', max_length=255)),
            ],
            options={
                'verbose_name': 'Class_in_School',
                'verbose_name_plural': 'Classes_Schools',
                'db_table': 'classes_schools',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('year', models.IntegerField(verbose_name='year')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'Semesters',
            },
        ),
        migrations.AlterModelOptions(
            name='teachersjobhistory',
            options={'verbose_name': 'TeacherJobHistory', 'verbose_name_plural': 'Teachers_Job_History'},
        ),
        migrations.CreateModel(
            name='TeachersCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.courses')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semesters')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teachers')),
            ],
            options={
                'verbose_name': 'Teacher_Course',
                'verbose_name_plural': 'Teachers_Courses',
                'db_table': 'teacher_courses',
            },
        ),
        migrations.CreateModel(
            name='StudentsTakenCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.courses')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semesters')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.students')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teachers')),
            ],
            options={
                'verbose_name': 'Student_Taken_Course',
                'verbose_name_plural': 'Students_Taken_Courses',
                'db_table': 'students_taken_courses',
            },
        ),
        migrations.CreateModel(
            name='StudentsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('cause', models.TextField(blank=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.classesschools')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.students')),
            ],
            options={
                'verbose_name': 'Student_History',
                'verbose_name_plural': 'Students_History',
                'db_table': 'students_history',
            },
        ),
        migrations.CreateModel(
            name='StudentsCoursesGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='year')),
                ('grade', models.IntegerField(verbose_name='Grade')),
                ('letter_grade', models.CharField(max_length=10, verbose_name='Letter_Grade')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.courses')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semesters')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.students')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teachers')),
            ],
            options={
                'verbose_name': 'Student_Course_Grade',
                'verbose_name_plural': 'Students_Courses_Grades',
                'db_table': 'students_courses_grades',
            },
        ),
        migrations.CreateModel(
            name='SchoolsSystemCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
            ],
            options={
                'verbose_name': 'School_System_Calendar',
                'verbose_name_plural': 'Schools_SystemCalendar',
                'db_table': 'schools_system_calendars',
            },
        ),
        migrations.CreateModel(
            name='SchoolsClassTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('year', models.IntegerField(verbose_name='year')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
            ],
            options={
                'verbose_name': 'SchoolsClassTime',
                'verbose_name_plural': 'Schools_ClassTimes',
                'db_table': 'schools_class_times',
            },
        ),
        migrations.CreateModel(
            name='SchedulesSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('year', models.IntegerField(verbose_name='year')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.classesschools')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.courses')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools')),
                ('semester_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semesters')),
                ('time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schoolsclasstimes')),
            ],
            options={
                'verbose_name': 'Schedule_in_School',
                'verbose_name_plural': 'Schedules_Schools',
                'db_table': 'schedules_in_schools',
            },
        ),
        migrations.AddField(
            model_name='classesschools',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.schools'),
        ),
    ]
